language: php

matrix:
    fast_finish: true
    include:
        - php: 8.0

install:
    - phpenv config-rm xdebug.ini || echo 'xdebug not available'
    - composer install
    - |
        for file in `find benchmarks/*/composer.json`; do
            cd `dirname ${file}`;
            composer install --optimize-autoloader --classmap-authoritative;
            cd ../..;
        done

script:
    - ./vendor/bin/phpbench run --report=bench

